"""empty message

Revision ID: 4be59aa859a6
Revises: 160a5b135191
Create Date: 2025-12-16 20:53:39.947935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be59aa859a6'
down_revision = '160a5b135191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planeta_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'planet', ['planeta_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('planeta_id')

    # ### end Alembic commands ###
