"""empty message

Revision ID: 7a4c7df5d553
Revises: 4be59aa859a6
Create Date: 2025-12-18 20:14:48.724281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a4c7df5d553'
down_revision = '4be59aa859a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('favorite_people_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'people', ['person_id'], ['id'])
        batch_op.drop_column('people_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_people_id_fkey', 'people', ['people_id'], ['id'])
        batch_op.drop_column('person_id')

    # ### end Alembic commands ###
